name: Build C# Backup Executables

on:
  push:
    branches:
      - master

permissions:
  packages: write
  contents: write

jobs:
  build:
    name: Build for ${{ matrix.rid }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            rid: linux-x64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish self-contained binary
        run: |
          dotnet publish -c Release -r ${{ matrix.rid }} \
            --self-contained true \
            -p:PublishReadyToRun=true \
            -p:PublishSingleFile=true \
            -o publish/${{ matrix.rid }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AnsibleRunner-${{ matrix.rid }}
          path: publish/${{ matrix.rid }}
          
      - name: Test
        run: cd publish/${{ matrix.rid }}/ && ls -a
          
      - uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: "true"
          tag_name: ${{ github.run_id }}
          name: "Release for ${{ github.run_id }}"
          generate_release_notes: true
          files: |
            publish/${{ matrix.rid }}/AnsibleRunner-${{ matrix.rid }}
            
            